### ISSUE TITLE
Is there a way to use nested CSS in .vue files?

### ISSUE THREAD

**Issue by Mr-Nobody-li** [Uninen/vite-ts-tailwind-starter#227]
I want to use nested CSS in .vue files like this
```
...
<style>
.a{
  .b{
    color:red
  }
}
</style>
```
but got error `} expectedcss(css-rcurlyexpected)` cause I used nested css
I don't know if using `postcss-nested` or `postcss-nesting` can avoid errors and make it work?

**Comment by Uninen** [comment]
The style-tag needs an attribute for the particular CSS preprocessor you're using so that the parser can figure it out. If you use PostCSS (like this repo is configured), you can use `<style lang="postcss">` to mark the tag as PostCSS instead of plain CSS.

See: https://vuejs.org/api/sfc-spec.html#pre-processors
